### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pleappleappleap** [linkedin/migz#8]
Hi!

```
root@wendigo:/data/snc_backups/full/temp# pv stream.gz | /home/ayengar/munzip | mbstream -x -v
Decompressing stdin using 32 threads
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:344)
        at com.linkedin.migz.MiGzInputStream.readFromInputStream(MiGzInputStream.java:222)
        at com.linkedin.migz.MiGzInputStream.decompressorThreadWithInflater(MiGzInputStream.java:172)
        at com.linkedin.migz.MiGzInputStream.decompressorThread(MiGzInputStream.java:114)
        at com.concurrentli.Interrupted.lambda$ignored$1(Interrupted.java:48)
        at java.base/java.lang.Thread.run(Thread.java:829)
72.0KiB 0:00:00 [ 725KiB/s] [>                                                                                                                             ]  0%            
root@wendigo:/data/snc_backups/full/temp#
```

'Nuff said?

**Comment by jsomeara** [comment]
Same thing here!

**Comment by jsomeara** [comment]
Version: 2.0.beta-1

**Comment by denizk** [comment]
Seems to affect both versions v1.0.4 and v2.0.beta-1

#### v1.0.4
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:395)
        at software.amazon.awssdk.utils.async.InputStreamSubscriber.read(InputStreamSubscriber.java:116)
        at software.amazon.awssdk.http.async.AbortableInputStreamSubscriber.read(AbortableInputStreamSubscriber.java:67)
        at software.amazon.awssdk.core.io.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
        at com.linkedin.migz.MiGzInputStream.readFromInputStream(MiGzInputStream.java:222)
        at com.linkedin.migz.MiGzInputStream.decompressorThreadWithInflater(MiGzInputStream.java:172)
        at com.linkedin.migz.MiGzInputStream.decompressorThread(MiGzInputStream.java:114)
        at com.concurrentli.Interrupted.lambda$ignored$1(Interrupted.java:48)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

#### v2.0.beta-1
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:395)
        at software.amazon.awssdk.utils.async.InputStreamSubscriber.read(InputStreamSubscriber.java:116)
        at software.amazon.awssdk.http.async.AbortableInputStreamSubscriber.read(AbortableInputStreamSubscriber.java:67)
        at software.amazon.awssdk.core.io.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
        at com.concurrentli.ManagedStreamReadBlocker.block(ManagedStreamReadBlocker.java:109)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3118)
        at com.concurrentli.ManagedStreamReadBlocker.read(ManagedStreamReadBlocker.java:41)
        at com.concurrentli.ManagedStreamReadBlocker.read(ManagedStreamReadBlocker.java:57)
        at com.linkedin.migz.MiGzInputStream$DecompressTask.decompressorThread(MiGzInputStream.java:264)
        at com.linkedin.migz.MiGzInputStream$DecompressTask.compute(MiGzInputStream.java:202)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by zleonov** [comment]
I am getting the same error when opening a normal gzip file.
